
services:
  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data/auth:/var/lib/postgresql/data
      - ./data/auth/logs:/var/log/postgresql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - auth-network

  social-db:
    image: neo4j:5.26.10-community-ubi9
    container_name: social-db
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    volumes:
      - ./data/social/data:/data
      - ./data/social/logs:/logs
      - ./data/social/plugins:/plugins
      - ./data/social/conf:/conf
    networks:
      - social-network
    healthcheck:
      test: [ "CMD-SHELL", "cypher-shell -u neo4j -p ${NEO4J_AUTH} 'RETURN 1'" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-service:
    image: bitnami/kafka:4.0.0
    container_name: kafka-service
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-service:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-service:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - '9094:9094'
    volumes:
      - ./data/kafka:/bitnami/kafka
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --bootstrap-server kafka-service:9092 --list" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    networks:
    - social-network
    - auth-network

networks:
  auth-network:
    driver: bridge
  social-network:
    driver: bridge