
services:
  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data/auth:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - auth-network

  social-db:
    image: neo4j:5.26.10-community-ubi9
    container_name: social-db
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    volumes:
      - ./data/social/data:/data
      - ./data/social/logs:/logs
      - ./data/social/plugins:/plugins
      - ./data/social/conf:/conf
    networks:
      - social-network
    healthcheck:
      test: [ "CMD-SHELL", "cypher-shell -u neo4j -p ${NEO4J_AUTH} 'RETURN 1'" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  auth-network:
    driver: bridge
  social-network:
    driver: bridge