spring:
  application:
    name: social-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: ${NEO4J_PASSWORD}
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: social-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: dev.edu.ngochandev.socialservice.kafka.events.UserRegisteredEvent
server:
  port: 8081