spring:
  application:
    name: social-service
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: social-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "dev.edu.ngochandev.common.events.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: dev.edu.ngochandev.common.events.UserRegisteredEvent
  data:
    mongodb:
      uri: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@localhost:27017/social_db?authSource=admin
server:
  port: 8081

openapi:
  service:
    api-docs: social-service
    server: http://localhost:${server.port}
    title: Social Service
    version: 1.0.0

jwt:
  access-token-secret: ${ACCESS_TOKEN_SECRET}
