spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/auth/**, /api/v1/users/**, /api/v1/roles/**, /api/v1/permissions/**, /swagger-ui/**, /v3/api-docs/auth-service/**
            - id: social-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/user-profile/**

server:
  port: 8888

app:
  security:
    internal-secret-key: ${INTERNAL_SECRET_KEY}
    public-endpoints:
      - /api/auth/register
      - /api/auth/authenticate
      - /api/auth/reset-password
      - /api/auth/forgot-password
      - /api/auth/verify-email
      - /swagger-ui/.*
      - /v3/api-docs/.*
      - /api/auth/verify-token